# Uncomment the next line to define a global platform for your project
platform :ios, '13.6'

target 'DrPhil Controller' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DrPhil Controller
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'

  target 'DrPhil ControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DrPhil ControllerUITests' do
    # Pods for testing
  end

end
