<?xml version="1.0" ?>
<robot name="dr-phil" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find dr_phil_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find dr_phil_description)/urdf/dr-phil.gazebo.xacro"/>



  <!-- strut measurements -->
  <xacro:property name="strut_short_length" value="0.035"/>
  <xacro:property name="strut_long_length" value="0.045"/>
  <xacro:property name="strut_screw_depth" value="0.0045"/>
  <xacro:property name="layer_3_strut_length" value="${strut_long_length}"/>
  <xacro:property name="layer_2_strut_length" value="${strut_long_length}"/>
  <xacro:property name="layer_1_strut_length" value="${strut_long_length}"/>
  <xacro:property name="plate_z" value="0.009"/>

  <xacro:property name="diameter_base" value="0.256"/>
  <xacro:property name="base_footprint_to_front_strut_plane" value="0.06405"/>
  <xacro:property name="base_footprint_to_back_strut_plane" value="${diameter_base - base_footprint_to_front_strut_plane}"/>
  <xacro:property name="base_footprint_to_side_strut_plane" value="0.115"/>
  <xacro:property name="base_footprint_to_3rd_layer_z" value="0.09140"/>
  <xacro:property name="base_footprint_to_geometric_centre" value="0.064"/>
  <xacro:property name="front_to_strut_1" value="0.012"/>
  <xacro:property name="front_to_strut_2" value="0.024"/>
  <xacro:property name="side_to_strut_3" value="${diameter_base / 4}"/>

  <!-- plate measurements -->
  <xacro:property name="layer_3_z" value="${(plate_z * 2) + (layer_1_strut_length + layer_2_strut_length + layer_3_strut_length) - (2 * 2 * strut_screw_depth)}"/>

  <!-- arm measurements -->
  <xacro:property name="px100_from_centre_to_back_box" value="0.04678"/>
  <xacro:property name="px100_back_box_width" value="0.08107"/>

  <xacro:property name="attachment_frame" value="base_link"/>

  <xacro:property name="arm_origin">
      <origin xyz="${-base_footprint_to_geometric_centre + px100_from_centre_to_back_box + (px100_back_box_width / 2)} 0 ${layer_3_z + plate_z}" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="arm_base_frame" value="base_arm"/>

  <xacro:include filename="$(find dr_phil_description)/urdf/px100.urdf.xacro" />


  <!-- dr_phil_description -->
  <link name="base_footprint">
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.010" rpy="0 0 0"/>
  </joint>


  <link name="base_link">
    <visual>
      <origin xyz="-0.064 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://dr_phil_description/meshes/bases/waffle_pi_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <!-- 3rd layer -->
    <visual>
      <origin xyz="-0.064 0 ${layer_3_z}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://dr_phil_description/meshes/bases/waffle_pi_base_layer.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <!-- strut 1 - front left -->
    <xacro:strut xyz="${base_footprint_to_front_strut_plane} ${front_to_strut_1} ${base_footprint_to_3rd_layer_z + (layer_3_strut_length/2)}" rpy="0 0 0" length="${layer_3_strut_length}"/>
    <!-- strut 2 - front right -->
    <xacro:strut xyz="${base_footprint_to_front_strut_plane} ${-front_to_strut_2} ${base_footprint_to_3rd_layer_z + (layer_3_strut_length/2)}" rpy="0 0 0" length="${layer_3_strut_length}"/>
    
    <!-- strut 3 - right side front -->
    <xacro:strut xyz="${-base_footprint_to_geometric_centre + side_to_strut_3} ${-base_footprint_to_side_strut_plane} ${base_footprint_to_3rd_layer_z + (layer_3_strut_length/2)}" rpy="0 0 0" length="${layer_3_strut_length}"/>
    <!-- strut 4 - right side back -->
    <xacro:strut xyz="${-base_footprint_to_geometric_centre - side_to_strut_3} ${-base_footprint_to_side_strut_plane} ${base_footprint_to_3rd_layer_z + (layer_3_strut_length/2)}" rpy="0 0 0" length="${layer_3_strut_length}"/>

    <!-- strut 5 - back right -->
    <xacro:strut xyz="${-base_footprint_to_back_strut_plane} ${-front_to_strut_1} ${base_footprint_to_3rd_layer_z + (layer_3_strut_length/2)}" rpy="0 0 0" length="${layer_3_strut_length}"/>
    <!-- strut 6 - back left -->
    <xacro:strut xyz="${-base_footprint_to_back_strut_plane} ${front_to_strut_2} ${base_footprint_to_3rd_layer_z + (layer_3_strut_length/2)}" rpy="0 0 0" length="${layer_3_strut_length}"/>
    
    <!-- strut 7 - left side front -->
    <xacro:strut xyz="${-base_footprint_to_geometric_centre + side_to_strut_3} ${base_footprint_to_side_strut_plane} ${base_footprint_to_3rd_layer_z + (layer_3_strut_length/2)}" rpy="0 0 0" length="${layer_3_strut_length}"/>
    <!-- strut 8 - left side back -->
    <xacro:strut xyz="${-base_footprint_to_geometric_centre - side_to_strut_3} ${base_footprint_to_side_strut_plane} ${base_footprint_to_3rd_layer_z + (layer_3_strut_length/2)}" rpy="0 0 0" length="${layer_3_strut_length}"/>

   
    <inertial>
      <!-- original value: xyz: 0,0,0 -->
      <origin xyz="-0.05 0 0" rpy="0 0 0"/>
      <!-- original value: 1.3729096e+00-->
      <mass value="1.3729096e+00"/>
      <inertia ixx="8.7002718e-03" ixy="-4.7576583e-05" ixz="1.1160499e-04"
               iyy="8.6195418e-03" iyz="-3.5422299e-06"
               izz="1.4612727e-02" />
    </inertial>
  </link>
  
  
  
  
  
  <joint name="bottle_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="bottle_base_link" />
    <origin xyz="0 0 0.010" rpy="0 0 0"/>
  </joint>


  <link name="bottle_base_link">
    <visual>
      <origin xyz="-0.088 -0.028 ${layer_3_z-0.0075}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://dr_phil_description/meshes/spray_components/bottle_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="-0.088 -0.028 ${layer_3_z-0.0075}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://dr_phil_description/meshes/spray_components/bottle_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="-0.088 -0.028 ${layer_3_z-0.0075}" rpy="0 0 0"/>
      <mass value="0.036"/>
      <inertia ixx="0.00" iyy="0.00" izz="0.000" ixy="0.0000000000" ixz="0.0000000000" iyz="0" />
    </inertial>
  </link>
  
  <joint name="bottle_joint" type="fixed">
    <parent link="bottle_base_link"/>
    <child link="bottle_link" />
    <origin xyz="0 0 0.010" rpy="0 0 0"/>
  </joint>


  <link name="bottle_link">
    <visual>
      <origin xyz="-0.1695 -0.0965 ${layer_3_z}" rpy="0 0 ${pi/2}"/>
      <geometry>
        <mesh filename="package://dr_phil_description/meshes/spray_components/bottle_reduced_resized.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="-0.1695 -0.0965 ${layer_3_z}" rpy="0 0 ${pi/2}"/>
      <geometry>
        <mesh filename="package://dr_phil_description/meshes/spray_components/bottle_reduced_resized.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-0.1695 -0.0965 ${layer_3_z}" rpy="0 0 0"/>
      <mass value="0.074"/>
      <inertia ixx="0.00" iyy="0.00" izz="0.000" ixy="0.0000000000" ixz="0.0000000000" iyz="0" />
    </inertial>
  </link>
  
  <joint name="bottle_cap_joint" type="fixed">
    <parent link="bottle_base_link"/>
    <child link="bottle_cap_link" />
    <origin xyz="0 0 0.010" rpy="0 0 0"/>
  </joint>


  <link name="bottle_cap_link">
    <visual>
      <origin xyz="-0.1519 -0.06 ${layer_3_z+0.096}" rpy="${pi} 0 0"/>
      <geometry>
        <mesh filename="package://dr_phil_description/meshes/spray_components/bottle_lid.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="-0.1519 -0.06 ${layer_3_z+0.096}" rpy="${pi} 0 0"/>
      <geometry>
        <mesh filename="package://dr_phil_description/meshes/spray_components/bottle_lid.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-0.1519 -0.06 ${layer_3_z+0.096}" rpy="0 0 0"/>
      <mass value="0.016"/>
      <inertia ixx="0.00" iyy="0.00" izz="0.000" ixy="0.0000000000" ixz="0.0000000000" iyz="0" />
    </inertial>
  </link>
  
  
  
  

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://dr_phil_description/meshes/wheels/left_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://dr_phil_description/meshes/wheels/right_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="caster_back_right_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_right_link"/>
    <origin xyz="-0.177 -0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_right_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="caster_back_left_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_left_link"/>
    <origin xyz="-0.177 0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_left_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.064 0 0.122" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://dr_phil_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="0.073 -0.011 0.084" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <collision>
      <origin xyz="0.005 0.011 0.013" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.030 0.027"/>
      </geometry>
    </collision>
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="0.003 0.011 0.009" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

</robot>
