arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
  gains: # Required because we're controlling an effort interface
    joint1: {p: 100.0,  d: 0.5, i: 5.0}
    joint2: {p: 500.0,  d: 0.5, i: 10.0}
    joint3: {p: 300.0,  d: 0.0, i: 10.0}
    joint4: {p: 100.0,  d: 0.0, i: 3.0}

  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint1: {trajectory: 0.1, goal: 0.1}
      joint2: {trajectory: 0.1, goal: 0.1}
      joint3: {trajectory: 0.1, goal: 0.1}
      joint4: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

# arm_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - joint1
#     - joint2
#     - joint3
#     - joint4
#   constraints:
#       goal_time: 0.6
#       stopped_velocity_tolerance: 0.05
#       joint1: {trajectory: 0.1, goal: 0.1}
#       joint2: {trajectory: 0.1, goal: 0.1}
#       joint3: {trajectory: 0.1, goal: 0.1}
#       joint4: {trajectory: 0.1, goal: 0.1}
#   stop_trajectory_duration: 0.5
#   state_publish_rate:  25
#   action_monitor_rate: 10
