# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Setup ROS environment
        uses: betwo/github-setup-catkin@master
        with:
          ros-version: 'noetic'
          build-tool: 'catkin_tools'
          workspace: '$GITHUB_WORKSPACE/ros-workspace'
          
      - name: Build catkin workspace
        run: cd $GITHUB_WORKSPACE/ros-workspace && catkin_make
        
      - name: Run tests
        run: cd ros-workspace && catkin_make run_tests
        
      - name: Save logs
        uses: actions/upload-artifact@v1            # upload logs
        with:
          name: catkin-logs
          path: ros-workspace
        if: always()
      
