# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:focal
    steps:
      - name: Setup ROS environment 
        uses: ros-tooling/setup-ros@0.1.2           
        with:
          required-ros-distributions: noetic    
          
      - uses: actions/checkout@v2
      
      - name: build and test ROS1 
        id: action_ros_ci_step
        uses: ros-tooling/action-ros-ci@0.1.1
        with:
          package-name: dr_phil_hardware dr_phil_gazebo
          target-ros1-distro: noetic
          import-token: ${{ secrets.REPO_TOKEN }}
          vcs-repo-file-url: ""
          
      - uses: actions/upload-artifact@v1            # upload logs
        with:
          name: colcon-logs
          path: ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/log
      - if: always()
      
