# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:focal
    steps:
      - name: Setup ROS                             # setup ROS install
        uses: ros-tooling/setup-ros@0.1.2           
        with:
          required-ros-distributions: noetic
      - run: "vcs --help"                           # confirm install
      
      - uses: actions/checkout@v1                   # checkout our repo
      - run: |                                      # generate dependencies
          source /opt/ros/noetic/setup.bash && 
          rosinstall_generator dr_phil_hardware --rosdistro noetic \
          --deps-only --deps --upstream-development > /tmp/deps.repos
          
      - name: Run Tests                             # run tests
        id: action_ros_ci_step
        uses: ros-tooling/action-ros-ci@0.1.1
        with:
          package-name: dr_phil_hardware
          target-ros1-distro: noetic
          import-token: ${{ secrets.REPO_TOKEN }}
          vcs-repo-file-url: /tmp/deps.repos
          
      - uses: actions/upload-artifact@v1            # upload logs
        with:
          name: colcon-logs
          path: ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/log
