controller_list:
  - name: fake_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_gripper_controller
      - gripper
      
initial:  # Define initial robot poses.
  - group: arm
    pose: default